Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,6 +1,8 @@
 name: Execução automação de testes
 
 on:
+  schedule:
+    - cron: '25 16 * * *'
   pull_request:
     types: [synchronize]
     paths-ignore:
@@ -50,10 +52,14 @@ jobs:
           echo "Node.js version: $(node --version)"
           echo "npx version: $(npx --version)"
 
-      - name: Cypress run 
-        uses: cypress-io/github-action@v2
-        with: 
-           command: npm run cypress:allure || exit 0
+      - name: Cypress run
+        id: cypress_run
+        run: |
+          npm run cypress:allure || exit 0
+          # Capture the exit code and set it as an output
+          # If Cypress run fails, it will still execute the subsequent steps
+        if: ${{ always() }}
+        shell: bash  
       # - name: Cypress run
       #   id: cypress_run
       #   run: |
