Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,25 +1,23 @@
 name: Execução automação de testes
 
 on:
-  schedule:
-    - cron: '* 10 * * 1-5'
   pull_request:
     types: [synchronize]
     paths-ignore:
-      - "**.md"
+      - '**.md'
   push:
     branches:
       - master
   workflow_dispatch:
     inputs:
       teste:
-        description: "Selecionar testes a serem executados: roteiro / test"
+        description: 'Selecionar testes a serem executados: roteiro / test'
         required: true
-        default: "test"
+        default: 'test'
       browser:
-        description: "Selecionar o browser: chrome / electron / firefox"
+        description: 'Selecionar o browser: chrome / electron / firefox'
         required: false
-        default: "chrome"
+        default: 'chrome'
 
 env:
   DEFAULT_TESTE: "roteiro"
@@ -32,51 +30,54 @@ jobs:
     container: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
     steps:
       - uses: actions/checkout@v2
-      - run: npm install
+      - run: npm install --verbose
 
       # Etapa de criação das pastas
       - run: mkdir -p cypress/videos
       - run: mkdir -p cypress/screenshots
       - run: mkdir -p cypress/report
+
       # Configuração da permissão
       - run: chmod -R a+w cypress/videos
       - run: chmod -R a+w cypress/screenshots
       - run: chmod -R a+w cypress/report
+
       - name: Debug info
         run: |
           echo "PATH: $PATH"
           echo "Node.js version: $(node --version)"
           echo "npx version: $(npx --version)"
 
-      - name: Cypress run
-        id: cypress_run
-        run: |
-          npm run cypress:allure || exit 0
-          # Capture the exit code and set it as an output
-            # If Cypress run fails, it will still execute the subsequent steps
-        if: ${{ always() }}
-        shell: bash
-        #  run: npm run cypress:allure
+      - name: Cypress run 
+        uses: cypress-io/github-action@v2
+        with: 
+           command: npm run cypress:allure || exit 0
+      # - name: Cypress run
+      #   id: cypress_run
+      #   run: |
+      #     npm run cypress:allure || exit 0
+      #     # Capture the exit code and set it as an output
+      #     # If Cypress run fails, it will still execute the subsequent steps
+      #   if: ${{ always() }}
+      #   shell: bash  
+      #  run: npm run cypress:allure 
         # command: npx cypress run --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
-        #  command: npm run ${{github.event.inputs.teste || env.DEFAULT_TESTE}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
+      #  command: npm run ${{github.event.inputs.teste || env.DEFAULT_TESTE}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
+    
 
       - name: Get Allure History
         uses: actions/checkout@v2
-        if: always()
         with:
           ref: gh-pages
-          path: gh-pages
+          path: allure-history
 
-      - name: Generate Allure Report
-        uses: simple-elf/allure-report-action@master
-        if: always()
-        with:
-          allure_results: allure-results
-          allure_history: allure-history
-          keep_reports: 20
+      # - name: Copy Allure report artifacts
+      #   run: |
+      #     mkdir -p allure-history
+      #     cp -r allure-results allure-history/results
+      #     cp -r allure-report allure-history/report
 
       - name: Deploy report to Github Pages
-        if: always()
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
@@ -88,6 +89,7 @@ jobs:
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: allure-history
+
       # - name: Enviar notificação Slack - Sucesso
       #   if: ${{ success() }}
       #   uses: rtCamp/action-slack-notify@v2
@@ -95,8 +97,8 @@ jobs:
       #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       #     SLACK_COLOR: ${{ job.status }}
       #     SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148767.png?size=48
-      #     SLACK_MESSAGE: "Sucesso na execução de testes do PR :white_check_mark:"
-      #     SLACK_TITlE: "Sucesso na execução de testes do PR :white_check_mark:"
+      #     SLACK_MESSAGE: 'Sucesso na execução de testes do PR :white_check_mark:'
+      #     SLACK_TITlE: 'Sucesso na execução de testes do PR :white_check_mark:'
       #     SLACK_USERNAME: SUCESS0
 
       # - name: Enviar notificação Slack - Falha
@@ -106,6 +108,6 @@ jobs:
       #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       #     SLACK_COLOR: ${{ job.status }}
       #     SLACK_ICON: https://cdn.icon-icons.com/icons2/1378/PNG/512/dialogerror_92823.png?size=48
-      #     SLACK_MESSAGE: "Falha na execução de testes do PR :fire:"
-      #     SLACK_TITlE: "Falha na execução de testes do PR :fire:"
+      #     SLACK_MESSAGE: 'Falha na execução de testes do PR :fire:'
+      #     SLACK_TITlE: 'Falha na execução de testes do PR :fire:'
       #     SLACK_USERNAME: FALHA
