Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,3 +1,125 @@
+# name: Execução automação de testes
+
+# on:
+#   schedule:
+#     - cron: '* 10 * * 1-5'
+#   pull_request:
+#     types: [synchronize]
+#     paths-ignore:
+#       - '**.md'
+#   push:
+#     branches:
+#       - master
+#   workflow_dispatch:
+#     inputs:
+#       teste:
+#         description: 'Selecionar testes a serem executados: roteiro / test'
+#         required: true
+#         default: 'test'
+#       browser:
+#         description: 'Selecionar o browser: chrome / electron / firefox'
+#         required: false
+#         default: 'chrome'
+
+# env:
+#   DEFAULT_TESTE: "roteiro"
+#   DEFAULT_BROWSER: "chrome"
+
+# jobs:
+#   test:
+#     name: Cypress run
+#     runs-on: ubuntu-latest
+#     container: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
+#     steps:
+#       - uses: actions/checkout@v2
+#       - run: npm install --verbose
+#       - run: npm uninstall cypress@12.17.4
+#       - run: npm install cypress@12.14.0
+
+#       # Etapa de criação das pastas
+#       - run: mkdir -p cypress/videos
+#       - run: mkdir -p cypress/screenshots
+#       - run: mkdir -p cypress/report
+
+#       # Configuração da permissão
+#       - run: chmod -R a+w cypress/videos
+#       - run: chmod -R a+w cypress/screenshots
+#       - run: chmod -R a+w cypress/report
+
+#       - name: Debug info
+#         run: |
+#           echo "PATH: $PATH"
+#           echo "Node.js version: $(node --version)"
+#           echo "npx version: $(npx --version)"
+
+#       - name: Cypress run
+#         id: cypress_run
+#         run: |
+#           npm run cypress:allure || exit 0
+#           # Capture the exit code and set it as an output
+#           # If Cypress run fails, it will still execute the subsequent steps
+#         if: ${{ always() }}
+#         shell: bash  
+#       # - name: Cypress run
+#       #   id: cypress_run
+#       #   run: |
+#       #     npm run cypress:allure || exit 0
+#       #     # Capture the exit code and set it as an output
+#       #     # If Cypress run fails, it will still execute the subsequent steps
+#       #   if: ${{ always() }}
+#       #   shell: bash  
+#       #  run: npm run cypress:allure 
+#         # command: npx cypress run --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
+#       #  command: npm run ${{github.event.inputs.teste || env.DEFAULT_TESTE}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
+    
+
+#       - name: Get Allure History
+#         uses: actions/checkout@v2
+#         with:
+#           ref: gh-pages
+#           path: allure-history
+
+#       # - name: Copy Allure report artifacts
+#       #   run: |
+#       #     mkdir -p allure-history
+#       #     cp -r allure-results allure-history/results
+#       #     cp -r allure-report allure-history/report
+
+#       - name: Deploy report to Github Pages
+#         uses: peaceiris/actions-gh-pages@v3
+#         with:
+#           github_token: ${{ secrets.GITHUB_TOKEN }}
+#           PUBLISH_BRANCH: gh-pages
+#           publish_dir: allure-history
+#           keep_files: true
+#         env:
+#           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+#           PUBLISH_BRANCH: gh-pages
+#           PUBLISH_DIR: allure-history
+
+#       # - name: Enviar notificação Slack - Sucesso
+#       #   if: ${{ success() }}
+#       #   uses: rtCamp/action-slack-notify@v2
+#       #   env:
+#       #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+#       #     SLACK_COLOR: ${{ job.status }}
+#       #     SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148767.png?size=48
+#       #     SLACK_MESSAGE: 'Sucesso na execução de testes do PR :white_check_mark:'
+#       #     SLACK_TITlE: 'Sucesso na execução de testes do PR :white_check_mark:'
+#       #     SLACK_USERNAME: SUCESS0
+
+#       # - name: Enviar notificação Slack - Falha
+#       #   if: ${{ failure() }}
+#       #   uses: rtCamp/action-slack-notify@v2
+#       #   env:
+#       #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+#       #     SLACK_COLOR: ${{ job.status }}
+#       #     SLACK_ICON: https://cdn.icon-icons.com/icons2/1378/PNG/512/dialogerror_92823.png?size=48
+#       #     SLACK_MESSAGE: 'Falha na execução de testes do PR :fire:'
+#       #     SLACK_TITlE: 'Falha na execução de testes do PR :fire:'
+#       #     SLACK_USERNAME: FALHA
+
 name: Execução automação de testes
 
 on:
@@ -31,20 +153,25 @@ jobs:
     runs-on: ubuntu-latest
     container: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
     steps:
-      - uses: actions/checkout@v2
-      - run: npm install --verbose
-      - run: npm uninstall cypress@12.17.4
-      - run: npm install cypress@12.14.0
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+      
+      - name: Install dependencies and Cypress
+        run: |
+          npm install --verbose
+          npm uninstall cypress@12.17.4
+          npm install cypress@12.14.0
 
-      # Etapa de criação das pastas
-      - run: mkdir -p cypress/videos
-      - run: mkdir -p cypress/screenshots
-      - run: mkdir -p cypress/report
-
-      # Configuração da permissão
-      - run: chmod -R a+w cypress/videos
-      - run: chmod -R a+w cypress/screenshots
-      - run: chmod -R a+w cypress/report
+      - name: Prepare directories and permissions
+        run: |
+          mkdir -p cypress/videos
+          mkdir -p cypress/screenshots
+          mkdir -p cypress/report
+          chmod -R a+w cypress/videos
+          chmod -R a+w cypress/screenshots
+          chmod -R a+w cypress/report
 
       - name: Debug info
         run: |
@@ -54,36 +181,15 @@ jobs:
 
       - name: Cypress run
         id: cypress_run
-        run: |
-          npm run cypress:allure || exit 0
-          # Capture the exit code and set it as an output
-          # If Cypress run fails, it will still execute the subsequent steps
+        run: npm run cypress:allure || exit 0
         if: ${{ always() }}
-        shell: bash  
-      # - name: Cypress run
-      #   id: cypress_run
-      #   run: |
-      #     npm run cypress:allure || exit 0
-      #     # Capture the exit code and set it as an output
-      #     # If Cypress run fails, it will still execute the subsequent steps
-      #   if: ${{ always() }}
-      #   shell: bash  
-      #  run: npm run cypress:allure 
-        # command: npx cypress run --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
-      #  command: npm run ${{github.event.inputs.teste || env.DEFAULT_TESTE}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
-    
+        shell: bash
 
       - name: Get Allure History
         uses: actions/checkout@v2
         with:
           ref: gh-pages
           path: allure-history
-
-      # - name: Copy Allure report artifacts
-      #   run: |
-      #     mkdir -p allure-history
-      #     cp -r allure-results allure-history/results
-      #     cp -r allure-report allure-history/report
 
       - name: Deploy report to Github Pages
         uses: peaceiris/actions-gh-pages@v3
@@ -97,25 +203,3 @@ jobs:
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: allure-history
-
-      # - name: Enviar notificação Slack - Sucesso
-      #   if: ${{ success() }}
-      #   uses: rtCamp/action-slack-notify@v2
-      #   env:
-      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-      #     SLACK_COLOR: ${{ job.status }}
-      #     SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148767.png?size=48
-      #     SLACK_MESSAGE: 'Sucesso na execução de testes do PR :white_check_mark:'
-      #     SLACK_TITlE: 'Sucesso na execução de testes do PR :white_check_mark:'
-      #     SLACK_USERNAME: SUCESS0
-
-      # - name: Enviar notificação Slack - Falha
-      #   if: ${{ failure() }}
-      #   uses: rtCamp/action-slack-notify@v2
-      #   env:
-      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-      #     SLACK_COLOR: ${{ job.status }}
-      #     SLACK_ICON: https://cdn.icon-icons.com/icons2/1378/PNG/512/dialogerror_92823.png?size=48
-      #     SLACK_MESSAGE: 'Falha na execução de testes do PR :fire:'
-      #     SLACK_TITlE: 'Falha na execução de testes do PR :fire:'
-      #     SLACK_USERNAME: FALHA
